
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/openbankxfxs
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false



logging.file.name=logs/openbankx.log


logging.level.root=INFO




logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n


logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n


app.jwt.secret=MySuperSecureJwtSecretKeyWithAtLeast32Chars!!

app.jwt.expiration-ms=3600000
